export const BOOTCAMP_LIST_REQUEST = "BOOTCAMP_LIST_REQUEST";
export const BOOTCAMP_LIST_SUCCESS = "BOOTCAMP_LIST_SUCCESS";
export const BOOTCAMP_LIST_FAIL = "BOOTCAMP_LIST_FAIL";
export const BOOTCAMP_LIST_RESET = "BOOTCAMP_LIST_RESET";

export const BOOTCAMP_DETAILS_REQUEST = "BOOTCAMP_DETAILS_REQUEST";
export const BOOTCAMP_DETAILS_SUCCESS = "BOOTCAMP_DETAILS_SUCCESS";
export const BOOTCAMP_DETAILS_FAIL = "BOOTCAMP_DETAILS_FAIL";
export const BOOTCAMP_DETAILS_RESET = "BOOTCAMP_DETAILS_RESET";

export const BOOTCAMP_DELETE_REQUEST = "BOOTCAMP_DELETE_REQUEST";
export const BOOTCAMP_DELETE_SUCCESS = "BOOTCAMP_DELETE_SUCCESS";
export const BOOTCAMP_DELETE_FAIL = "BOOTCAMP_DELETE_FAIL";

export const BOOTCAMP_CREATE_REQUEST = "BOOTCAMP_CREATE_REQUEST";
export const BOOTCAMP_CREATE_SUCCESS = "BOOTCAMP_CREATE_SUCCESS";
export const BOOTCAMP_CREATE_FAIL = "BOOTCAMP_CREATE_FAIL";
export const BOOTCAMP_CREATE_RESET = "BOOTCAMP_CREATE_RESET";

export const BOOTCAMP_UPDATE_REQUEST = "BOOTCAMP_UPDATE_REQUEST";
export const BOOTCAMP_UPDATE_SUCCESS = "BOOTCAMP_UPDATE_SUCCESS";
export const BOOTCAMP_UPDATE_FAIL = "BOOTCAMP_UPDATE_FAIL";
export const BOOTCAMP_UPDATE_RESET = "BOOTCAMP_UPDATE_RESET";

export const BOOTCAMP_CREATE_REVIEW_REQUEST = "BOOTCAMP_CREATE_REVIEW_REQUEST";
export const BOOTCAMP_CREATE_REVIEW_SUCCESS = "BOOTCAMP_CREATE_REVIEW_SUCCESS";
export const BOOTCAMP_CREATE_REVIEW_FAIL = "BOOTCAMP_CREATE_REVIEW_FAIL";
export const BOOTCAMP_CREATE_REVIEW_RESET = "BOOTCAMP_CREATE_REVIEW_RESET";
