export const MY_COURSE_LIST_REQUEST = "MY_COURSE_LIST_REQUEST";
export const MY_COURSE_LIST_SUCCESS = "MY_COURSE_LIST_SUCCESS";
export const MY_COURSE_LIST_FAIL = "MY_COURSE_LIST_FAIL";
export const MY_COURSE_LIST_RESET = "MY_COURSE_LIST_RESET";

export const MY_COURSE_DETAILS_REQUEST = "MY_COURSE_DETAILS_REQUEST";
export const MY_COURSE_DETAILS_SUCCESS = "MY_COURSE_DETAILS_SUCCESS";
export const MY_COURSE_DETAILS_FAIL = "MY_COURSE_DETAILS_FAIL";
export const MY_COURSE_DETAILS_RESET = "MY_COURSE_DETAILS_RESET";

export const MY_COURSE_DELETE_REQUEST = "MY_COURSE_DELETE_REQUEST";
export const MY_COURSE_DELETE_SUCCESS = "MY_COURSE_DELETE_SUCCESS";
export const MY_COURSE_DELETE_FAIL = "MY_COURSE_DELETE_FAIL";
export const MY_COURSE_DELETE_RESET = "MY_COURSE_DELETE_RESET";

export const MY_COURSE_CREATE_REQUEST = "MY_COURSE_CREATE_REQUEST";
export const MY_COURSE_CREATE_SUCCESS = "MY_COURSE_CREATE_SUCCESS";
export const MY_COURSE_CREATE_FAIL = "MY_COURSE_CREATE_FAIL";
export const MY_COURSE_CREATE_RESET = "MY_COURSE_CREATE_RESET";

export const MY_COURSE_UPDATE_REQUEST = "MY_COURSE_UPDATE_REQUEST";
export const MY_COURSE_UPDATE_SUCCESS = "MY_COURSE_UPDATE_SUCCESS";
export const MY_COURSE_UPDATE_FAIL = "MY_COURSE_UPDATE_FAIL";
export const MY_COURSE_UPDATE_RESET = "MY_COURSE_UPDATE_RESET";

export const MY_COURSE_CREATE_REVIEW_REQUEST =
	"MY_COURSE_CREATE_REVIEW_REQUEST";
export const MY_COURSE_CREATE_REVIEW_SUCCESS =
	"MY_COURSE_CREATE_REVIEW_SUCCESS";
export const MY_COURSE_CREATE_REVIEW_FAIL = "MY_COURSE_CREATE_REVIEW_FAIL";
export const MY_COURSE_CREATE_REVIEW_RESET = "MY_COURSE_CREATE_REVIEW_RESET";
